# docker-compose.yml

version: '3.8'

services:
  service1:
    build:
      context: ./service_1
    container_name: golang_service
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/ping"]
      interval: 10s
      retries: 3

  service2:
    build:
      context: ./service_2
    container_name: python_service
    ports:
      - "8002:8002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]
      interval: 10s
      retries: 3

  nginx:
    build:
      context: ./nginx
    container_name: nginx_reverse_proxy
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
